sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VgA8gJhyqr5PFjQ8wdyYJ8W5NwsDyXd5GvUvJm3CmPcyN9zmsQuGGgSXhACCGCBJ9E/w0+YaIBGEdv75ewKuCb6dKPEh7b3zo8BDv2CPvsS6VyDo0hm5bES6KkGT/a658b3WEkDF8vT652BF+XZH+fyfm28pkFuC6uvJ9p0GaXj6npsO6XM+RvErj5bWam/RxeVcgVZi6REl3nWykcFcpbrFbuRjbSPZn1qO82vRh3tm40qL43rRW4G0E0mRE0ZEUYXvKvmQIus3wfrMUxwICffHwEe/tBksjiwCO/brZh1ZKWaOwgf5HSwj1yNg8UogA8lQOmMLmEBMJlX81hJKWVfegDM8D/1X5dnue2ioGfgV+n7wwLzvUKPJV4b15JahrVtfg9PM1jUjbHMHA58i1rBu8v4trYBtR7JRmsk5ux+n6L3jYw91i9jmZFvPSefYR7RwrvXgymGV8aCTZGw0a6bhVM5kswjggb9Daym7UR+yG1OYG4z+e+QWF/DxJ7mtSLq70toySqsfQfwCyS0vPLcPmTWwGWPN/68rkQnEHQJF3NAG0cf8jamL5MwWTCdzt2ogg0PbAmhAxuKiialo2XRZNqMFmoJlqmA/YehXfn10Ur3WvIsuxUFNttbdib2W7JHDu8N9ULBZ7oifcaTevj9P2fEhkimEVJvHgLBfdkY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Christie-Johnstone--A-Novel_3671
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy